# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6908aa993ce1ce40b47afbe61fd2aef56d4c54c16d4df7e651c4ef5c35ff3fbf9b914cd184d792fd42bfae4bb6c8e29f4d09921bebfce13e7eed7491d9cd35e

test:
  secret_key_base: fa4cf21c19534b3b967d6e5e0b8e4e0625fef2d884941149441183948444e688778acf8e90b2fa445cfa284f942eb895da3e86145200d1c2281a46125854b49b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
